Feature/better bullets
hackerspace-ntnu/Prosjekt-Spill-H22 pull request #144
Opened 2023-04-03 23:51 UTC by SondreHus

TLDR: Things are a but rough around the edges, but this branch is quickly becoming too big for a single feature.

- Reworked the system so it no longer initializes projectiles as gameobjects
- Made new vfx systems that replace the old gameobjects visually
- Made nice pretty muzzle flash and smoke trail 

Stuff that needs more work:
- Mesh projectile does not appear consistently when initialized, needs a bugfix
- Max-sizes of particles trips and particle numbers currently manually set in vfx instances, should be set using script for stable development
- Need a texture2D Array equivalent to allow more than one bullet to be initialized at once for future shotguns.

PS: If any of you bastards are nitpicky about this pull request I will annihilate you. It is somewhat unfinished, since it is way too large as it is, and new features need to work from the new projectile baseline sooner rather than later.

PPS: I know how to make pipe bombs, don't test me.

2023-04-04 15:04 UTC, toberge requested changes
Playtested and I have some :warning: **major concerns** :warning: 

- Projectiles **don't actually damage players** anymore
- Reload doesn't work, after you've fired all your bullets you're simply **unable to fire again**
- Guns with multiple outputs are treated as if they have *one* output

While the smoke trails and muzzle flashes look great, I can't accept merging code that *actually breaks the game*. We should fix these issues promptly, though keep in mind that you don't need to be the only one working on this :sweat_smile: 

I've tried to refrain from nitpicking, but in the end I left a couple of the more serious nitpicks for you :kissing_heart:

2023-04-05 23:54 UTC, SondreHus commented on Assets/Scripts/Augment/GunFactory.cs
> +        gunController.projectile.projectileOutput = gunController.outputs[0];
Yup, temporarily

2023-04-05 23:54 UTC, SondreHus commented on Assets/Scripts/Augment/GunController.cs
> -        onFire?.Invoke(stats);
Fixed

2023-04-05 23:56 UTC, SondreHus commented on Assets/Scripts/Augment/BulletController.cs
> +                HitboxController hitbox = collisions[0].GetComponent<HitboxController>();
It is hitscan, it does the entirety of the path at once, one discrete step at a time, updating the vfx as it goes, cool huh?

2023-04-05 23:57 UTC, SondreHus commented on Assets/Scripts/Augment/BulletController.cs
> +    public override void InitializeProjectile(GunStats stats)
We need an entire new system to deal with this issue.

2023-04-05 23:58 UTC, SondreHus commented on Assets/Scripts/Augment/GunModifier.cs
> +public class GunModifier : MonoBehaviour
Correct, will remove it

2023-04-05 23:58 UTC, SondreHus commented on Assets/Scripts/Augment/GunController.cs
> +    public Transform projectileOutput;
Like mentioned, the output system needs a rework, not gonna to it in this branch

2023-04-07 11:00 UTC, toberge commented on Assets/Scripts/Augment/GunModifier.cs
> +public class GunModifier : MonoBehaviour
Um sorry but it's still here?

2023-04-07 12:01 UTC, Fueredoriku requested changes
I have encountered som unmentioned issues:
- Guns that shoot meshes (hat) seem to have the particle it clones active and viewable when initialized:
![image](https://user-images.githubusercontent.com/54811121/230603746-638fd68b-89b5-4dcd-9544-6715ad31054e.png)
- The gun always initializes with two extensions instead of 1, shown below with the fire extension:
![image](https://user-images.githubusercontent.com/54811121/230603978-5888094b-381a-4253-8033-cd17a9c5aba7.png)
- Fire extension doesn't instantiate flames onHit anymore? 🤔

2023-04-08 09:59 UTC, toberge approved these changes
Needs a few adjustments that could be done later (and should be added as issues), but it's good enough to replace our current _very bad_ projectiles :))))))

2023-04-12 17:43 UTC, Fueredoriku approved these changes
Seems like the double extension problem has been resolved! 👍

We'll make the fire extension update it's own separate issue.

Tested and works on my machine, great work! 🤠

2023-04-12 17:44 UTC, SondreHus reviewed
Fixed

2023-04-12 17:49 UTC, merged