Feature/post match scoring
hackerspace-ntnu/Prosjekt-Spill-H22 pull request #191
Opened 2023-05-06 15:35 UTC by TArchetype

Pull request contains a post match scoring system.

closes #171

2023-05-08 11:42 UTC, Fueredoriku commented
Bidding is broken due to playerIdentity somehow no longer being transported from FPS to bidding. This must be fixed before approve

![image](https://user-images.githubusercontent.com/54811121/236814832-e485983b-ebce-41ac-8a18-99cc205eab9d.png)

2023-05-08 11:43 UTC, toberge requested changes
A few major usability issues:

- The death screen for the last death in a round doesn't show. We should make it clear who died and allow the winner to style on them.
- In a similar vein, there is no delay before switching to bidding. We should wait a little before going there.

2023-05-08 12:19 UTC, Fueredoriku requested changes
This is a nice feature, and the panning is really smooth! 👍

There are some issues that need to be adressed, mainly that the way you call/use MatchController breaks parts of the game, so I would personally try to implemement the call to TownScoreBoard on the end of a round as an async operation that is await-ed in MatchController instead.  

Also the "crime" naming scheme for variables in TownScoreBoard and Poster classes is a bit confusing to me.
The scoreboard in the scene should also be made into a prefab.

This branch also need to be rebased before merge.

2023-05-08 12:19 UTC, Fueredoriku commented on Assets/Scripts/Gamestate/MatchController.cs
> -
This should not have been moved from matchManager into TownScoreBoard. The reason it was structured this way initialy was to ensure the all functions subscribed to the onRoundEnd delegate were invoked before we changed the scene. 

Now important functions like the one that decouples and transfers playerInput isn't able to be executed before players scene is changed. This leads to the bidding scene being broken.

2023-05-08 12:19 UTC, Fueredoriku commented on Assets/Scripts/Gamestate/MatchController.cs
> -        if (!IsWin())
Removing this makes it impossible to win a match.

2023-09-25 16:22 UTC, ThomasJGabrielsen commented
Closed for major overhaul

2023-09-25 16:22 UTC, closed without merging